<a href="https://colab.research.google.com/github/jelade/AMMI_PROJECT1_G8/blob/main/Jaleel__pytorch_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

The objective of this session is to practice with basic tensor manipulations in pytorch, to understand the
relation between a tensor and its underlying storage, and get a sense of the efficiency of tensor-based
computation compared to their equivalent python iterative implementations

In [ ]:
import torch

## 1- Multiple views of a storage

Generate the following matrix with no python loop

$
\begin{bmatrix}
1 & 2 & 1 & 1 & 1 & 1 & 2 & 1 & 1 & 1 & 1 & 2 & 1\\
2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2\\
1 & 2 & 1 & 1 & 1 & 1 & 2 & 1 & 1 & 1 & 1 & 2 & 1\\
1 & 2 & 1 & 3 & 3 & 1 & 2 & 1 & 3 & 3 & 1 & 2 & 1\\
1 & 2 & 1 & 3 & 3 & 1 & 2 & 1 & 3 & 3 & 1 & 2 & 1\\
1 & 2 & 1 & 1 & 1 & 1 & 2 & 1 & 1 & 1 & 1 & 2 & 1\\
2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2\\
1 & 2 & 1 & 1 & 1 & 1 & 2 & 1 & 1 & 1 & 1 & 2 & 1\\
1 & 2 & 1 & 3 & 3 & 1 & 2 & 1 & 3 & 3 & 1 & 2 & 1\\
1 & 2 & 1 & 3 & 3 & 1 & 2 & 1 & 3 & 3 & 1 & 2 & 1\\
1 & 2 & 1 & 1 & 1 & 1 & 2 & 1 & 1 & 1 & 1 & 2 & 1\\
2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2 & 2\\
1 & 2 & 1 & 1 & 1 & 1 & 2 & 1 & 1 & 1 & 1 & 2 & 1\\
\end{bmatrix}
$

**Hint**:  Use `torch.full`, and the slicing operator.

In [ ]:
w = torch.full((13,13),1)
w[(1,-2),:] = 2
w[:,(1,-2)] = 2
w[:,6] = 2
w[6,:] = 2
w[3:5,3:5]= 3
w[-4:-2,-4:-2] = 3
w[3:5,-4:-2] = 3
w[-5:-3,3:5]= 3

In [ ]:

w

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 1, 3, 3, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 1, 3, 3, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 1, 3, 3, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 3, 3, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])

## 2- Eigen decomposition

Without using python loops, create a square matrix $M$ (a 2d tensor) of dimension 20 × 20, filled with
random Gaussian coefficients and  a diagonal matrix $D$ 


$D = \begin{bmatrix} 1 & 0 & 0 & \dots & 0 \\ 0 & 2 & 0 & \dots & 0 \\ 0 & 0 & 3 & \dots & 0 \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & 0 & \dots & 20 \end{bmatrix}$

Compute the eigen values of:

\begin{equation*}
M^{-1} D
 M
\end{equation*}

**Hint**: Use `torch.empty`, `torch.normal_`, `torch.arange`, `torch.diag`, `torch.mm`, `torch.inverse`,
and `torch.linalg.eig`.

In [ ]:
M = torch.randn((20,20))
D = torch.arange(1,len(M)+1)
D = torch.diag(D).type(torch.float)
inv = torch.inverse(M).type(torch.float)


In [ ]:
mul = torch.mm(torch.inverse(M),D)
mull = torch.mm(mul,M)

In [ ]:
eigue = torch.empty(20)
eigue = torch.linalg.eig(mull)
eigue

torch.return_types.linalg_eig(
eigenvalues=tensor([ 1.0000+0.j, 20.0000+0.j,  2.0000+0.j, 19.0000+0.j, 18.0000+0.j, 17.0000+0.j,
         3.0000+0.j,  4.0000+0.j, 16.0000+0.j,  5.0000+0.j, 15.0000+0.j,  6.0000+0.j,
        14.0000+0.j,  7.0000+0.j,  8.0000+0.j,  9.0000+0.j, 11.0000+0.j, 10.0000+0.j,
        13.0000+0.j, 12.0000+0.j]),
eigenvectors=tensor([[ 3.9898e-02+0.j,  1.3182e-01+0.j, -2.5029e-01+0.j,  1.9064e-02+0.j,
         -1.8931e-01+0.j,  1.0830e-02+0.j,  5.1461e-03+0.j, -1.0797e-01+0.j,
          3.0513e-01+0.j, -8.7543e-02+0.j,  2.6841e-02+0.j,  9.7061e-02+0.j,
         -2.5143e-01+0.j, -7.3488e-03+0.j,  2.9072e-01+0.j,  2.2416e-01+0.j,
          4.2337e-01+0.j,  4.7875e-02+0.j,  2.4495e-02+0.j,  2.6145e-01+0.j],
        [ 5.4548e-02+0.j,  1.2166e-02+0.j, -5.6422e-02+0.j,  7.8289e-02+0.j,
          1.0763e-01+0.j, -1.3755e-01+0.j,  7.6955e-02+0.j, -1.1331e-01+0.j,
          1.4242e-01+0.j, -4.7749e-02+0.j,  1.7967e-02+0.j, -4.8928e-02+0.j,
         -1.5851e-01+0.j, -3.8608

##3- FLOPS per second

Generate two square matrices of dimension 5000 × 5000 filled with random Gaussian coefficients,
compute their product, measure the time it takes, and estimate how many floating point products
have been executed per second (should be in the billions or tens of billions).


**Hint**: Use `torch.empty`, `torch.normal_`, `torch.mm`, and `time.perf_counter`

In [ ]:
from time import perf_counter

In [ ]:
one = torch.randn(5000,5000)
two = torch.randn(5000,5000)
t1_start = perf_counter()
matmul= torch.mm(one,two)

t1_stop = perf_counter()


print("Elapsed time:", t1_stop, t1_start)
 
 
print("Elapsed time during the whole program in seconds:",t1_stop-t1_start)

floating_point = 7500*5000


print("floating point products have been executed per second:",floating_point/(t1_stop-t1_start))


Elapsed time: 4082.17670752 4078.363135932
Elapsed time during the whole program in seconds: 3.8135715879998315
floating point products have been executed per second: 9833301.705414755


## 4- Playing with strides

Write a function `mul_row`, using python loops (and not even slicing operators), that gets a 2d tensor
as argument, and returns a tensor of same size, whose first row is identical to the first row of the
argument tensor, the second row is multiplied by two, the third by three, etc.
For instance:



In [ ]:
m = torch.full((4, 8), 2.0)
m

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]])

In [ ]:
def mul_row(x):
  # YOUR CODE HERE
  for i in torch.arange(len(x)):
    j = i+1
    x[i]*=j
  return x


Then, write a second version named `mul_row_fast`, using tensor operations.
Apply both versions to a matrix of size 1000 × 400 and measure the time each takes (there should
be more than two orders of magnitude difference).

**Hint**: Use broadcasting and `torch.arange`, `torch.view`, `torch.mul`, and `time.perf_counter`.

In [ ]:
t1_start = perf_counter()
mul_row(m)

t1_stop = perf_counter()


print("Elapsed time:", t1_stop, t1_start)
 
 
print("Elapsed time during the whole program in seconds:",t1_stop-t1_start)


Elapsed time: 5663.219948588 5663.219264921
Elapsed time during the whole program in seconds: 0.000683666999975685


In [ ]:
def mul_row_fast(x):
  l = torch.arange(1,len(x)+1).view(len(x),-1)
  mat = torch.mul(x,l)
  return mat

In [ ]:
mul_row_fast(m)

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
t1_start = perf_counter()
mul_row_fast(m)

t1_stop = perf_counter()


print("Elapsed time:", t1_stop, t1_start)
 
 
print("Elapsed time during the whole program in seconds:",t1_stop-t1_start)

Elapsed time: 5692.883198356 5692.88266523
Elapsed time during the whole program in seconds: 0.0005331259999366011


I learnt that pytorch is very fast and its easy to use like numpy. Also, using pytorch operation is faster than using for loop.